# Internal event names to look up upon user selection
event_choices = {
    "Ace League": ["ace", "mace"],
    "Ace League (no mirror)": ["ace"],
    "Classic": ["classic"],
    "Classic Mini-Prix": ["classicprix"],
    "Glitch 99": [
        "glitch99",
        "Mystery_3",
        "Mystery_4",
        "Mystery_5",
        "Mystery_6",
        "Mystery_7",
    ],
    "Grand Prix": [
        "ace",
        "mace",
        "knight",
        "mknight",
        "queen",
        "mqueen",
        "king",
        "mking",
    ],
    "Hard Tracks": ["protracks"],
    "King League": ["king", "mking"],
    "King League (no mirror)": ["king"],
    "Knight League": ["knight", "mknight"],
    "Knight League (no mirror)": ["knight"],
    "Queen League (no mirror)": ["queen"],
    "Mirror Ace League": ["mace"],
    "Mirror King League": ["mking"],
    "Mirror Knight League": ["mknight"],
    "Mirror Queen League": ["mqueen"],
    "Mini-Prix": ["classicprix", "miniprix", "mysteryprix"],
    "Pro-Tracks": ["protracks"],
    "Queen League": ["queen", "mqueen"],
    "Retro": ["classic"],
    "Secret League": ["glitchgp"],
    "Team Battle": ["teambattle"],
    "World Tour": ["worldtour"],
}


# Internal mini-prix types to look up upon user selection
mp_event_choices = {
    "Classic Mini-Prix": "classicprix",
    "Mini-Prix": "miniprix",
    "Private Classic Mini-Prix": "classicprix",
    "Private Mini-Prix": "miniprix",
}


mp_track_choices = {
    "Big Blue": "Big_Blue",
    "Big Blue II": "Big_Blue_II",
    "Big Blue + Red Canyon": "Mystery_5",
    "Death Wind I": "Death_Wind_I",
    "Death Wind II": "Death_Wind_II",
    "Death Wind White Land": "Mystery_3",
    "Fire City": "Mystery_4",
    "Mute City I": "Mute_City_I",
    "Mute City II": "Mute_City_II",
    "Mute City III": "Mute_City_III",
    "Mute City IV": "Mute_City_IV",
    "Port Town I": "Port_Town_I",
    "Port Town II": "Port_Town_II",
    "Red Canyon I": "Red_Canyon_I",
    "Red Canyon II": "Red_Canyon_II",
    "Sand Ocean": "Sand_Ocean",
    "Sand Ocean + Port Town": "Mystery_6",
    "Sand Storm I": "Sand_Storm_I",
    "Sand Storm II": "Sand_Storm_II",
    "Silence + Sand Storm": "Mystery_7",
    "White Land I": "White_Land_I",
}


cmp_track_choices = {
    "Big Blue": "Big_Blue",
    "Big Blue II": "Big_Blue_II",
    "Death Wind I": "Death_Wind_I",
    "Death Wind II": "Death_Wind_II",
    "Fire Field": "Fire_Field",
    "Mute City I": "Mute_City_I",
    "Mute City II": "Mute_City_II",
    "Mute City III": "Mute_City_III",
    "Mute City IV": "Mute_City_IV",
    "Port Town I": "Port_Town_I",
    "Port Town II": "Port_Town_II",
    "Red Canyon I": "Red_Canyon_I",
    "Red Canyon II": "Red_Canyon_II",
    "Sand Ocean": "Sand_Ocean",
    "Sand Storm I": "Sand_Storm_I",
    "Sand Storm II": "Sand_Storm_II",
    "Silence": "Silence",
    "Silence II": "Silence_II",
    "White Land I": "White_Land_I",
    "White Land II": "White_Land_II",
}
